### ISSUE TITLE
Kiwoom 객체 생성 시 오류

### ISSUE THREAD

**Issue by hhebb** [breadum/kiwoom#10]
`Kiwoom()` 으로 객체 만들 때 

`Canceled future for execute_request message before replies were done`

문구와 함께 에러가 발생합니다.

터미널에서 실행 테스트 했을 시에
`QWidget: Must construct a QApplication before a QWidget`
메시지를 출력하네요.

kiwoom 객체 생성 전에 QT app 먼저 실행해주니까 에러없이 실행됩니다~
`app = QApplication(sys.argv)`

**Comment by breadum** [comment]
안녕하세요,

아래 문구는 말씀주신 대로 app 객체를 먼저 생성하셔야 합니다.
`QWidget: Must construct a QApplication before a QWidget`

실행 스크립트 기본 구조를 참조하시면 좋을 것 같습니다. 
[튜토리얼](https://github.com/breadum/kiwoom/tree/main/tutorials) 보시면 확인 가능합니다.
```
if __name__ == '__main__':
    # 통신을 위해 QApplication 이용
    app = QApplication(sys.argv)
    # 인스턴스 생성
    bot = MyBot(MyServer())
    # 로그인
    bot.run()
    # 통신 유지를 위해 스크립트 종료 방지
    app.exec()
```  
  
--------   
  
`Canceled future for execute_request message before replies were done' `  
키움 서버에 데이터 요청한 후 데이터를 전달 받기 전에 다른 요청을 또 보낸 것 같습니다.  
Bot 클래스에서 요청 후 loop 하시고, Server 클래스에서 데이터 다 받으신 후 unloop 하셔야합니다.  

[tutorials/5. TR Data.py](https://github.com/breadum/kiwoom/blob/main/tutorials/5.%20TR%20Data.py) 튜토리얼에 자세한 코드가 있습니다.  
해당 메세지만 봐서는 답변에 한계가 있어서 양해 부탁드립니다.
혹시 안되시면 다시 문의주세요~
