### ISSUE TITLE
실시간 목록 - 주식체결  tutorials에 추가 부탁드립니다. 

### ISSUE THREAD

**Issue by skindryang** [breadum/kiwoom#12]
실시간 목록 - 주식체결 신청하여 실시간 현재가를 받아올려고 하는데요 이게 맞는지 모르겠습니다. ㅠ
고견 부탁드립니다.

class Bot(Bot):
    def __init__(self, server):
        super().__init__(server)

        self.api.set_connect_hook('on_receive_real_data', 'real_type')
        self.api.connect('on_receive_real_data', signal=self.real_price, slot=self.server.real_price)

    def real_price():
        self.api.set_real_reg("2000", "005930;005380", "10", "0")   #삼성전자;현대차  10:현재가
        print('주가체결 구독')

class Server(Server):
    def __init__(self):
        super().__init__()
        self.downloading = False

    def real_price():
        for code in code_list:
            real_dict={code:{}}
            current_price = self.api.get_comm_real_data(code, '10')
            real_dict[code].update({'현재가':current_price})

if __name__ == '__main__':
    app = QApplication(sys.argv)
    bot = Bot(Server())
    bot.login()
    bot.account()
    bot.balance()
    bot.real_price()

**Comment by breadum** [comment]
안녕하세요,
일정이 바뻐서 답변이 늦었습니다.

Hook을 쓰시면 이렇게 사용하실 수 있습니다.
```
self.api.set_connect_hook('on_receive_real_data', 'real_type') 
self.api.connect('on_receive_real_data', signal=self.real_price, slot=self.server.real_price,
key='주식체결')
```

아래는 다른 방법으로 구현한 예시이니 필요에 맞게 변형하시면 됩니다.
```
from time import sleep
from PyQt5.QtWidgets import QApplication
from kiwoom import Bot, Server

class Server(Server):
    def on_receive_real_data(self, code, real_type, _):
        if real_type == '주식체결':
            prc = self.api.get_comm_real_data(code, 10)
            # self.share.extend_multi('real_price', code, prc)  # 현재가 list
            self.share.update_single('real_price', code, prc)  # 현재가

class Bot(Bot):
    def register(self, codes):
        self.api.set_real_reg(
            scr_no='2000',
            code_list=codes,
            fid_list='10',
            opt_type='0'
        )

    def real_price(self, code):
        try:
            # return self.share.get_multi('real_price', code)  # 현재가 list 
            return self.share.get_single('real_price', code)  # 현재가
        except KeyError:
            return f'현재가 데이터를 수신하지 못했습니다. : {code} '

    def run(self):
        self.register('005930;005380')
        for i in range(5):
            print(bot.real_price('005930'))
            print(bot.real_price('005380'))
            sleep(3)
        
if __name__ == '__main__':
    app = QApplication([])
    bot = Bot(Server())
    bot.run()
```

현재가는 장중에만 가능하니 시도해보시고 안되면 다시 말씀주세요.
감사합니다.
