### ISSUE TITLE
조건검색 hook 처리 문의

### ISSUE THREAD

**Issue by atmoskr** [breadum/kiwoom#13]
조건검색은 OnReceiveConditionVer, OnReceiveTrCondition,OnReceiveRealCondition 등의 slot들  처리함에 있어서

        self.api.set_connect_hook('on_receive_tr_condition', param='condition_name')
        self.api.connect('on_receive_tr_condition', slot=self.server.test_condition1)

        self.api.set_connect_hook('on_receive_real_condition', param='condition_name')
        self.api.connect('on_receive_real_condition', slot=self.server.test_condition1)

위같이 하면, self.server 내에서 조건식명이 같기 때문에(test_condition1) 함수명을 어떻게 처리하나요 (중복)?

**Comment by breadum** [comment]
안녕하세요, 
답변이 늦어서 죄송합니다.

두 이벤트 함수가 받는 인자들이 달라서 하나의 slot으로는 처리할 수 없습니다.
각각의 함수로 만드셔야 하지만 꼭 위 방법으로 하셔야겠다면,
아래처럼 구현해 볼 수 있을것 같은데 권장드리지는 않습니다.

```
def test_condition1(self, *args):  
    if len(args) == 5:  
        # on_receive_tr_condition
        # args = (scr_no, code_list, condition_name, index, next)
    if len(args) == 4:
        # on_receive_real_condition
        # args = (code, type, condition_name, condition_index)
```

말씀주신 튜토리얼은 요즘 시간이 많이 없어서 당분간은 힘들것 같습니다ㅠ

**Comment by atmoskr** [comment]
각각의 함수로 만든다는 의미가 이해가 잘 안가는데요, send_condition을 실시간으로 하면 on_receive_tr_condition과 on_receive_real_condition 두 함수 모두 call이 되도록 되어있는데, 원래 의도하신 대로라면 저 4줄 코드가 어떻게 바뀌어야 하는지요?

**Comment by breadum** [comment]
위에 코드가 문제 없다면 그대로 쓰셔도 되고, 
두 이벤트 함수 각각에 대해 콜백 함수를 작성하셔도 됩니다. 

```
from kiwoom import Bot, Server

class Slot(Server):
    # on_receive_tr_condition
    def test_condition1_tr(self, scr_no, code_list, condition_name, index, next): 
        pass

    # on_receive_real_condition
    def test_condition1_real(self, code, type, condition_name, condition_index):
        pass

class Bot(Bot):
    def __init__(self):
        super().__init__(Slot())
        self.api.set_connect_hook('on_receive_tr_condition', param='condition_name')
        self.api.connect(
            'on_receive_tr_condition', 
            slot=self.server.test_condition1_tr, 
            key='test_condition1'
        )

        self.api.set_connect_hook('on_receive_real_condition', param='condition_name')
        self.api.connect(
            'on_receive_real_condition', 
            slot=self.server.test_condition1_real,
            key='test_condition1'
        )
        
if __name__ == '__main__':
    bot = Bot()
```
___ 
각각의 이벤트 함수에서 특정 인자를 hook으로 설정해두면,
해당 인자로 들어오는 값에 따라서 slot 함수로 매핑됩니다. 
위의 예시에서는 condition_name 값에 따라 매핑됩니다.
`self.api.set_connect_hook('on_receive_tr_condition', param='condition_name')`

이 상태에서 connect 함수로 이벤트와 slot을 연결하게 되면, 
기본 값으로 slot 함수 이름으로 condition_name의 키값이 매핑되게 됩니다. 
`self.api.connect('on_receive_tr_condition', slot=self.server.test_condition1)`

다시 말해서, 이벤트가 호출될 때 주어진 condition_name의 값이 'test_condition1' 이면,
server.test_condition1 함수가 자동으로 매핑되어 호출됩니다. 

그런데 기본 키값은 slot 함수 이름이지만 말씀주신 경우처럼 중복되는 경우에는
connect() 하실 때 key 옵션을 활용하여 매핑을 변경할 수 있습니다.
```
self.api.connect(
    'on_receive_tr_condition', 
    slot=self.server.test_condition1_tr, 
    key='test_condition1'
)
```

**Comment by atmoskr** [comment]
그런 방법이 있었군요~~; 잘 동작 하네요. 완전 감사.
