### ISSUE TITLE
'실시간 체결 데이터' 수신 slot의 unloop 실행과 관련하여 문의 드립니다.

### ISSUE THREAD

**Issue by kimtaeduck** [breadum/kiwoom#18]
bot에서 ready_optsise(or SetRealReg 등록) 호출로 server slot이  '실시간 체결 데이터'(on_receive_real_data)를

    실시간 수신 받게 되면 계속 unloop가 거의 실시간 반복 실행되는 상황인데 굳이 unloop 지정 해야 하는지 ?

  => 실시간 수신 받으면서 계속 unloop실행됨으로 다른 함수의 unloop 실행을 가로채는 것 아닌지 ? 어찌 풀어야 할지 ?

  =>  도움 답변 감사합니다.

**Comment by breadum** [comment]
Bot.ready_optsise() 함수는 TR 요청을 한 후 데이터 수신 대기를 위해 loop() 함수가 필요하고, 
TR 요청 결과를 수신하는 on_receive_tr_data() 이벤트 호출 시 수신이 완료되었다면 unloop()이 필요합니다.

on_receive_tr_data(rq_name='ready_optsise') 일 때 Server.ready_optsise() 함수가 호출되도록 연결했다면, 
Server.ready_optsise() 함수에서 unloop() 함수를 호출해야 합니다.

다만, 이때 Bot.ready_optsise() 함수에 의해 on_receive_real_data() 이벤트가 부가적으로 발생한다면, 
on_receive_real_data() 함수에서는 실시간 데이터 처리 이벤트기 때문에 unloop()을 적용하지 않습니다.
그냥 실시간으로 데이터가 오는 대로 계속 처리하게 두면 됩니다. 

```
from kiwoom import Bot, Server

class Bot(Bot):
    def __init__(self, server):
        super().__init__(server)

        # on_receive_tr_data
        self.api.set_connect_hook('on_receive_tr_data', 'rq_name')
        self.api.connect(
            'on_receive_tr_data', 
            signal=self.ready_optsise,  
            slot=self.server.ready_optsise
        )

        # on_receive_real_data
        self.api.connect('on_receive_real_data',   slot=self.server.on_receive_real_data)

    def ready_optsise(self, *args):
        ...
        self.api.comm_rq_data('ready_optsise', tr_code, '0', scr_no)
        self.api.loop()


class Server(Server):
    def ready_optsise(self, scr_no, rq_name, tr_code, record_name, prev_next):
        ...
        self.api.unloop()

    def on_reeceive_real_data(self, code, real_type, real_data):
        # handle real data
        ...
```
