### ISSUE TITLE
피크 타임에 응답없음

### ISSUE THREAD

**Issue by BScarrot** [breadum/kiwoom#19]
안녕하세요?
실서버에서 구동중에
주로 9시 ~ 9시 15분 사이에
api/ set_real_reg
api/ set_real_remove
(실시간 시세 조회 및 해제) 
요청 시 빈번하게 전체 프로세스가 멈추는 현상이 있습니다.
( 3초마다 한번씩 API를 요청하여 빈도를 현저하게 낮추어도 동일하게 문제가 발생하고 있습니다.
  장초반 10~20종목 정도 set_real_reg로 등록합니다 )

해당 현상 발생시 catch_error로 오류이벤트가 발생하지 않고
멀티스레딩 중인 스케쥴러(로깅) 또한 함께 멈추는 것으로 보입니다.

디버깅을 어떻게 해야할지 
해당 원인이 키움 쪽에서 응답없음이라면,
어떤 식으로 대응해야할지 조언 부탁드립니다.

**Comment by breadum** [comment]
set_real_reg 사용으로 인한 것 보다는 TR 요청 시 loop / unloop 함수를 사용하는 과정에서 문제가 있지 않을까 하는데요. 멈추는 문제의 대부분은 이쪽인데 함수 콜스택을 로그로 찍어보시면 어떨까요?
