### ISSUE TITLE
판다스 32bit 지원 중지

### ISSUE THREAD

**Issue by SimpleRule** [breadum/kiwoom#20]
안녕하세요.
kiwoom 모듈을 설치 후 판다스 32bit 버전을 따로 설치하려고 할 때 판다스가 더이상 구버전의 wheel을 지원하지 않게 되어 설치가 불가한 것 같습니다. 그에 따라 kiwoom 모듈의 사용도 불가합니다.
이젠 더이상 kiwoom 모듈을 사용이 불가능한 건가요?

**Comment by breadum** [comment]
안녕하세요,
pandas 1.5 버전을 활용하시면 사용 가능합니다.

> pip uninstall pandas
> pip install "pandas<2"

**Comment by SimpleRule** [comment]
pip uninstall pandas
WARNING: Skipping pandas as it is not installed.

pip install pandas<2
지정된 파일을 찾을 수 없습니다.

이런 결과가 나오는군요.

**Comment by breadum** [comment]
아래처럼 string 처리해서 다시 한 번 해보시겠어요?
> pip install "pandas<2"
