### ISSUE TITLE
키움증권 Open API 파이썬

### ISSUE THREAD

**Issue by jetseo** [breadum/kiwoom#3]

**Comment by breadum** [comment]
안녕하세요 @jetseo 님,

혹시 코드에 문제가 있나요?

이슈가 있다면 말씀해 주시고, 

없다면 Issue#3 닫도록 하겠습니다.

감사합니다.

**Comment by jetseo** [comment]
아 깃헙 어플 처음이라서
잘못눌렀습니다
죄송합니다
