### ISSUE TITLE
 share.py  single내에 fn data가 있는지 없는지 확인 방법 ?

### ISSUE THREAD

**Issue by kimteaduck** [breadum/kiwoom#5]
share.py  single내에 fn data가 있는지 없는지 확인 방법 ?

**Comment by breadum** [comment]
Share 객체에서 single 혹은 multi 데이터 상세를 확인할 수 있는 방법을 추가했습니다.
주문 전송 관련 [6번 튜토리얼](https://github.com/breadum/kiwoom/blob/main/tutorials/6.%20Trading.py)에 같이 추가해 두었습니다.

```
# All single data for balance (방법1)
if bot.share.isin_single('balance'):
    print(bot.share.get_single('balance'))  # dict 
# Specific single data for balance
if bot.share.isin_single('balance', key='총평가손익금액'):
    print(bot.share.get_single('balance', key='총평가손익금액'))  # int
    
# All multi data for balance (방법2)
try:
    bot.share.get_multi('balance')  # dict
except KeyError:
    pass
# Specific multi data for balance
try:
    print(bot.share.get_multi('balance', key='종목명'))  # list[str]
except KeyError:
    pass
```


이메일로도 문의주신 부분 추가로 답변 같이 드립니다.

Share 클래스에 사용된 single, multi 데이터는 기본적으로 defaultdict이기 때문에,
주의하지 않으면 키를 확인하는 과정에서 없던 키들이 새로 생성될 수 있습니다.

서버와의 통신 과정에서 데이터 수신 여부를 확실히 하기 위해,
키가 없을 시 KeyError Exception이 발생해야 시스템이 좀 더 안정될 수 있다고 생각합니다.
때문에 에러 핸들링을 사용자가 직접 하도록 모듈을 구성하고 있습니다.
