### ISSUE TITLE
api.py SendOrderFO 주문 요청과 이벤트 처리 connect 하려고 하는데 방법 ?

### ISSUE THREAD

**Issue by kimteaduck** [breadum/kiwoom#6]
api.py SendOrderFO 주문 요청과 이벤트 처리 connect 하려고 하는데 아래와 같이 하면 적절한지요 ?
 rq_name 대신 gubun ??

        self.api.set_connect_hook('on_receive_chejan_data', 'gubun')           

        self.api.connect('on_receive_chejan_data', signal=self.orderfo, slot=self.server.orderfo)

       주문후 이벤트 처리하는 예제를 tutorials 에 추가해주시면 감사 감사 ~

**Comment by breadum** [comment]
주문 전송 관련 [6번 튜토리얼](https://github.com/breadum/kiwoom/blob/main/tutorials/6.%20Trading.py) 작성해 두었습니다.

기본적으로 hook을 설정하면 이벤트에서 특정 인자의 값으로 slot을 매핑합니다.
말씀 주신 방법으로 구현을 한다면 이렇게 해 볼 수 있을 것 같습니다.

주문 전송 후 gubun값은 '0', ' 1', '4'로 오게되는데 해당 값에 맞게 각각의 slot을 구현합니다.
각각의 slot 함수 안에서 self.api.get_chejan_data(fid)를 통해 수신 데이터를 활용하시면 됩니다.

'0' (접수/체결) : server.zero(self, gubun, item_cnt, fid_list)
'1' (잔고변경) : server.one(self, gubun, item_cnt, fid_list)
'4' (파생잔고) : server.four(self, gubun, item_cnt, fid_list)

그런 다음에 체결잔고 이벤트가 수신 되었을 때 (on_receive_chejan_data),
gubun 값에 따라 맞는 함수를 호출하기 위해 bot에서 connect 함수를 통해 매핑합니다.
```
self.api.set_connect_hook('on_receive_chejan_data', 'gubun')           
self.api.connect('on_receive_chejan_data', signal=None, slot=self.server.zero, key='0')
self.api.connect('on_receive_chejan_data', signal=None, slot=self.server.one, key='1')
self.api.connect('on_receive_chejan_data', signal=None, slot=self.server.four, key='4')
```

만약에 체결잔고 이벤트를 직접 모두 수신 하고 싶으시면 hook을 설정하지 않고,
이벤트에 직접 slot을 연결하는 방법이 있습니다. 튜토리얼에 작성해 두었습니다.
`self.api.connect('on_receive_chejan_data', slot=self.server.chejan)`

혹시 보시고 문제 있으면 말씀주세요.
이슈는 당분간 열어두겠습니다.
감사합니다.
