### ISSUE TITLE
 키움 해외주식선물 Python Wrapper 모듈 계획은 있는지요 ?

### ISSUE THREAD

**Issue by kimteaduck** [breadum/kiwoom#7]
키움 해외주식선물 Python Wrapper 모듈 계획은 있는지요 ?

**Comment by breadum** [comment]
해외주식선물 API 함수로 수정하면 그렇게 많이 걸리진 않을 것 같은데,
지금 여유가 많이 없어서 계획을 따로 잡고 있지는 않습니다.

대략적으로 아래 부분들을 수정하면 큰 작업은 끝날 것 같은데,
사실 테스트 해보면서 안정성 갖추는 부분이 더 오래 걸려서 어렵네요..

config/*
core/kiwoom
wrapper/api

혹시 모듈 Fork 하셔서 직접 도전 해보시는 것은 어떠신지요ㅎㅎ
관심 감사드립니다.
